### ISSUE TITLE
No local packages or download links found for abipy

### ISSUE THREAD

**Issue by linuxfreebird** [abinit/abipy#106]
$ sudo easy_install abipy
Searching for abipy
Reading https://pypi.python.org/simple/abipy/
No local packages or download links found for abipy
error: Could not find suitable distribution for Requirement.parse('abipy')

How do I get abipy to appear as a known package to install?

**Comment by adamjstewart** [comment]
Release 0.2.0 is now available on PyPI. Can you try again?
