### ISSUE TITLE
Cannot import name SlotPickleMixin from pymatgen 

### ISSUE THREAD

**Issue by cespejo79** [abinit/abipy#111]
Hello! 

I'm trying to run the example plot_bands.py from http://pythonhosted.org/abipy/examples/plot/plot_bands.html and gets the following error message:

python2.7 getbands.py 
Traceback (most recent call last):
  File "getbands.py", line 5, in <module>
    from abipy.abilab import abiopen
  File "/usr/local/lib/python2.7/dist-packages/abipy-0.1.0-py2.7.egg/abipy/**init**.py", line 18, in <module>
    from abipy.core import release
  File "/usr/local/lib/python2.7/dist-packages/abipy-0.1.0-py2.7.egg/abipy/core/**init**.py", line 2, in <module>
    from .kpoints import *
  File "/usr/local/lib/python2.7/dist-packages/abipy-0.1.0-py2.7.egg/abipy/core/kpoints.py", line 15, in <module>
    from pymatgen.serializers.pickle_coders import SlotPickleMixin
ImportError: cannot import name SlotPickleMixin

I just changed the script name to getbands.py. After searching in pymatgen source I found that in the file 

> /usr/local/lib/python2.7/dist-packages/pymatgen/serializers/pickle_coders.py

the function SlotPickleMixin is not defined. So, I'm wondering if I'm using the wrong or incompatible version of pymatgen. Thanks in advance,

Camilo.

**Comment by gmatteo** [comment]
Hi Camilo,

the version of abipy on github requires my fork of the pymatgen repository.
I'm developing in both projects and in some cases abipy requires new stuff that is only 
available in https://github.com/gmatteo/pymatgen
For the time being, I would suggest to fork https://github.com/gmatteo/pymatgen.git
and install this version of pymatgen with `python setup.py install` or `python setup.py develop`

**Comment by cespejo79** [comment]
Hi Matteo, 
thanks for the advise. Now abipy is working smoothly!

Cheers,

Camilo

**Comment by zbwang** [comment]
Hi Matteo,

I have this error (ImportError: cannot import name 'SlotPickleMixin) when running "from abipy.lessons.lesson_kpoint_convergence import Lesson". I checked the pymatgen doc and it seems there is no "SlotPickleMixin" in pymatgen.serializers.pickle_coders.

Could you help me fix this problem? thanks

Zhenbin

**Comment by zbwang** [comment]
Just an update, I solve the problem by changing "pymatgen.serializers.pickle_coders import SlotPickleMixin" to "pymatgen.serializers.pickle_coders import PmgPickler"

Thanks
Zhenbin

**Comment by gmatteo** [comment]
Fixed in abipy v0.2 that is now in synch with pymatgen 4.7.2
