### ISSUE TITLE
TypeError: read_dimvalue() got an unexpected keyword argument 'default'

### ISSUE THREAD

**Issue by zbwang** [abinit/abipy#113]
Hello abipy developers,

I have the following error when running the example code plot_bands.py (http://pythonhosted.org/abipy/examples/plot/plot_bands.html)

-----error-info-------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-6c6ba2c1fd9d> in <module>()
      8 
      9 # Open the GSR file and extract the band structure.
---> 10 with abiopen(filename) as ncfile:
     11     ebands = ncfile.ebands
     12 

/Users/wzb/repos/abipy/abipy/abilab.py in abiopen(filepath)
    189 
    190     cls = abifile_subclass_from_filename(filepath)
--> 191     return cls.from_file(filepath)
    192 
    193 

/Users/wzb/repos/abipy/abipy/electrons/gsr.py in from_file(cls, filepath)
     42     def from_file(cls, filepath):
     43         """Initialize the object from a Netcdf file"""
---> 44         return cls(filepath)
     45 
     46     def __init__(self, filepath):

/Users/wzb/repos/abipy/abipy/electrons/gsr.py in __init__(self, filepath)
     50 
     51         # Initialize the electron bands from file
---> 52         self._ebands = r.read_ebands()
     53 
     54         # Add forces to structure

/Users/wzb/repos/abipy/abipy/electrons/ebands.py in read_ebands(self)
   2358             nelect=self.read_nelect(),
   2359             nspinor=self.read_nspinor(),
-> 2360             nspden=self.read_nspden(),
   2361             nband_sk=self.read_nband_sk(),
   2362             smearing=self.read_smearing(),

/Users/wzb/repos/abipy/abipy/electrons/ebands.py in read_nspden(self)
   2374         """Number of spin-density components"""
   2375         # FIXME: default 1 is needed for SIGRES files (abinit8)
-> 2376         return self.read_dimvalue("number_of_components", default=1)
   2377 
   2378 

TypeError: read_dimvalue() got an unexpected keyword argument 'default'
------------------------------------------------------------------

Could you pls do me favor to look into this problem?
I am using Abipy-0.1.0 and Abinit-7.10.5

Thanks
Zhenbin

**Comment by gmatteo** [comment]
Fixed in v0.2
