### ISSUE TITLE
Launching ABINIT calculations with python 3

### ISSUE THREAD

**Issue by fgoudreault** [abinit/abipy#133]
Hi,

When using the Launcher object in python 3, there is a bug when writing the .sh file. I've submitted a PR #129  2 months ago that resolves this issue and I have not received any news. The details of the bug fix are located in the commits that comes with the PR.

Would it be possible to either merge this PR or resolve the issue?
Thanks

**Comment by GkAntonius** [comment]
Dear Félix,
Please beware that the Launcher and related objects in the htc submodule is deprecated, and will likely be removed. See the lessons for how to use the standard abipy objects. If you prefer the old scheme, I suggest you have a look at my own abitools module, in which I moved much of these objects that were part of abipy.htc.

**Comment by fgoudreault** [comment]
Thank you for your response. If this is deprecated, from now on I will use the objects as discussed in the tutorials. Perhaps a Deprecation Warning would be useful in the deprecated classes.
