### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels:

### ISSUE THREAD

**Issue by lcodacal** [abinit/abipy#174]
Hi,
   After successfully following the steps in the "Anaconda Howto" section (http://abinit.github.io/abipy/installation.html#contents), I got the following "strange" error message when trying to install abipy:
===============================================
[ogando@PedroBala:~]$ conda install abipy -c abinit
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - abipy
  - prettytable
  - abipy
  - pymatgen==2018.3.14

Current channels:

  - https://conda.anaconda.org/abinit/linux-64
  - https://conda.anaconda.org/abinit/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
===============================================

   Could you, please, help me ?
   All the best,
            Luis

**Comment by gmatteo** [comment]
Which python version are you using?
Activate the conda environment and then use `python --version`.

**Comment by lcodacal** [comment]
Hi,
   Thank you for your attention !
   The answer to your question is:

[ogando@PedroBala:~]$ source anaconda3/bin/activate root
(base) [ogando@PedroBala:~]$ python --version
Python 3.6.6 :: Anaconda, Inc.
(base) [ogando@PedroBala:~]$

   All the best,
                Luis


Em qua, 7 de nov de 2018 às 08:05, gmatteo <notifications@github.com>
escreveu:

**Comment by gmatteo** [comment]
I tried to install AbiPy with:
```
conda install abipy -c abinit
```
on Mac and Linux and python 3.6.6 and the installation completed successfully
(windows is not supported)
Did you add conda-forge and matsci to the default channels with

```
conda config --add channels conda-forge
conda config --add channels matsci
conda config --add channels abinit
```

If this does not solve your problem, you may try:

```
pip install abipy
```

inside your conda environment.

**Comment by lcodacal** [comment]
Thank you !
   It worked !
   It looks like the channels addition was the missing step.
   All the best,
             Luis


Em qua, 7 de nov de 2018 às 15:58, gmatteo <notifications@github.com>
escreveu:

**Comment by lcodacal** [comment]
I believe that I found the source of my mistake. If someone tries to
install AbiPy following the instructions in
http://abinit.github.io/abipy/installation#anaconda-howto   , the channels
addition step is absent (differently from  https://github.com/abinit/abipy
).
   Perhaps, including this step there will prevent other people bothering
you.
   Thank you again !
   All the best,
                 Luis

Em qua, 7 de nov de 2018 às 16:17, gmatteo <notifications@github.com>
escreveu:

**Comment by Motany-a** [comment]
> I tried to install AbiPy with:
> 
> ```
> conda install abipy -c abinit
> ```
> 
> on Mac and Linux and python 3.6.6 and the installation completed successfully
> (windows is not supported)
> Did you add conda-forge and matsci to the default channels with
> 
> ```
> conda config --add channels conda-forge
> conda config --add channels matsci
> conda config --add channels abinit
> ```
> 
> If this does not solve your problem, you may try:
> 
> ```
> pip install abipy
> ```
> 
> inside your conda environment.

This worked for me...
