### ISSUE TITLE
getting abipy to launch jobs on my computing server

### ISSUE THREAD

**Issue by GkAntonius** [abinit/abipy#180]
Dear devs,
I cannot get abipy to launch a job on my computing server. I believed that I set up the `manager.yml` and `scheduler.yml` properly.

I adapted the `run_relax.py` script for my needs, which creates a `flow_relax` directory and the job submission script `flow_relax/w0/t0/job.sh` is well formed and could be manually submitted with `sbatch`. However, I want to get `abirun.py` to submit the whole flow.

I tried: `abirun.py flow_relax single` or `abirun.py flow_relax rapid` or `abirun.py flow_relax scheduler`. In either case, it results in `AbiCritical` status, with an error message in the file `flow_relax/w0/t0/run.err` complaining about missing SLURM lines in the job script. Indeed, I can see that the file `flow_relax/w0/t0/job.sh` has been overwritten, because all the SLURM preemble that was in this file is now gone.

What is going on? Am I missing the basic usage here?

**Comment by gmatteo** [comment]
>  In either case, it results in AbiCritical status, with an error message in the file flow_relax/w0/t0/run.err complaining about missing SLURM lines in the job script. Indeed, I can see that the file flow_relax/w0/t0/job.sh has been overwritten

The script is overwritten because abipy calls abinit to get the list of possible parallel configurations and then sets the appropriate options in the submission script.
Perhaps there's some error at the level of the autoparal part (I hope you are using a version of Abinit with MPI support because the autoparal feature requires MPI)

Coud you post the output of

     abirun.py FLOWDIR history

and the error message found in run.err?

**Comment by GkAntonius** [comment]
The output of `abirun.py FLOWDIR history` would be:

    Running on beluga3.int.ets1.calculquebec.ca -- system Linux -- Python 3.6.3 -- abirun-0.6.0

    ===================================================================================================================================================================
    ======================================================== <RelaxTask, node_id=93, workdir=flow_relax/w0/t0> ========================================================
    ===================================================================================================================================================================
    [Tue Jun  4 09:57:07 2019] Status changed to Ready. msg: Status set to Ready
    [Tue Jun  4 09:57:07 2019] Setting input variables: {'autoparal': 1, 'max_ncpus': 240, 'mem_test': 0}
    [Tue Jun  4 09:57:07 2019] Old values: {'autoparal': None, 'max_ncpus': None, 'mem_test': None}
    [Tue Jun  4 09:57:09 2019] First call to autoparal failed with `[Errno 2] No such file or directory: '/home/antonius/Projects/PerformanceTests/Production/111-STO-relax-beluga/flow_relax/w0/t0/run.abo'`. Will try fix_abicritical
    [Tue Jun  4 09:57:09 2019] Status changed to Error. msg: We encountered AbiCritical events that could not be fixed
    [Tue Jun  4 09:57:09 2019] Status set to S_ABI_CRITICAL due to: fix_abicritical could not solve the problem
    [Tue Jun  4 14:55:11 2019] Found error message:
     srun: error:
    ----------------------------------------
    You are associated with multiple _cpu allocations...
    Please specify one of the following accounts to submit this job:

      RAS default accounts: def-cotemich, def-geadahan,
              RAC accounts: rrg-antonius, rrg-cotemich-ac,
    Compute-Burst accounts:
            Other accounts:

    Use the parameter --account=desired_account when submitting your job
    ----------------------------------------
    srun: error: Unable to allocate resources: Unspecified error

    [Tue Jun  4 14:55:11 2019] Status changed to Running. msg: final option: nothing seems to be wrong, the job must still be running

and the full content of `run.err` is contained in the message above. It means that the submission script does not contain the line `#SBATCH --account=rrg-antonius`. However, when I first create the directory, before I use `abirun.py`, the job script does contain this line.

For completeness, here is the content of my `manager.yml` file:

    hardware: &hardware
       num_nodes: 172
       sockets_per_node: 40
       cores_per_socket: 1
       mem_per_node: 92 Gb

    job: &job
       mpi_runner: srun
       modules:
           -  abinit/8.10.2
       shell_env:
            PATH: $PATH
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH

    qadapters:
      - priority: 1
        queue:
           qname:
           qtype: slurm
           qparams:
              {account : 'rrg-antonius'}
        limits:
           timelimit: 0:30:0
           min_cores: 40
           max_cores: 240
           min_mem_per_proc: 700
        hardware: *hardware
        job: *job

**Comment by GkAntonius** [comment]
Also, the file `flow_relax/w0/t0/queue.qerr` contains the following error message:

    The following modules were not unloaded:
      (Use "module --force purge" to unload all):
      
      1) StdEnv/2018.3     4) gcccore/.7.3.0      7) intel/2018.3
      2) nixpkgs/16.09     5) icc/.2018.3.222     8) openmpi/3.1.2
      3) imkl/2018.3.222   6) ifort/.2018.3.222

But that doesn't seem too problematic...

**Comment by gmatteo** [comment]
By default, the autoparal job is executed on the frontend with` srun` because your 
manager.yml uses 

```yaml
mpi_runner: srun
```
However, there are clusters in which users are now allowed to use `srun` on the frontend.
In this case, one can use the `shell_runner` option to change the command that will be prepended to abinit when running the code to get the autoparal configurations. 
 Can you try to set shell_runner to None to avoid using srun on the frontend?

This is an example of manager file I used on BlueGeneQ:

https://github.com/abinit/abipy/blob/develop/abipy/data/managers/jureca_manager.yml

**Comment by GkAntonius** [comment]
Thanks! Specifying the shell_runner did solve the problem.

Now, my `manager.yml` file looks like this:

    hardware: &hardware
       num_nodes: 172
       sockets_per_node: 1
       cores_per_socket: 40
       mem_per_node: 92 Gb

    job: &job
       mpi_runner: srun
       shell_runner: None
       modules:
           -  abinit/8.10.2
       shell_env:
            PATH: $PATH
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH

    qadapters:
      - priority: 1
        queue:
           qname:
           qtype: slurm
           qparams:
              {account : 'rrg-antonius'}
        limits:
           timelimit: 0:30:0
           min_cores: 1
           max_cores: 240
           min_mem_per_proc: 700
        hardware: *hardware
        job: *job

Thanks a lot!
