### ISSUE TITLE
abinit: error while loading shared libraries: libnetcdf.so.15

### ISSUE THREAD

**Issue by ylx1116** [abinit/abipy#196]
Dear devs:

Hope everything is going well. I've been following your recipe to install abinit and abipy using Anaconda. I am able to download install numpy, scipy, netcdf4, abipy and abinit from the Anaconda cloud linked to by the recipe with no issues. But when I try to run
`abinit --version`
I get the error: 

abinit: error while loading shared libraries: libnetcdf.so.15: cannot open shared object file: No such file or directory

When I search the shared library, I find libnetcdf.so.11 instead of libnetcdf.so.15. So it seems like abinit is not linking correctly to the shared library or I do not have the right version of netCDF in the shared library. I have tried both abinit 8.8.2 and 8.10.1 on the conda cloud to no avail. I am wondering if this is a issue with the abinit package on conda or if I am messing up the installation procedure. Is there any report of the same issue? What should I try next?

Best regards,
Alex

**Comment by chem-william** [comment]
Maybe not a complete fix, but I found that installing version 9.0.4 fixed it.

It is available [here](https://anaconda.org/conda-forge/abinit)
