### ISSUE TITLE
Where can i find WFK.nc?

### ISSUE THREAD

**Issue by ghost** [abinit/abipy#218]
So i think it's so stupid question, but where can I find WFK.nc file, in outputs files if have only WFK file without filename extension?

**Comment by gmatteo** [comment]
WFK without the `.nc` extension is a Fortran binary file. This format is not supported by AbiPy.
To produce a netcdf file i.e. `WFK.nc` you need to set `iomode` to.3 in the input file

**Comment by sportmasterofficial** [comment]
> 
> 
> WFK without the `.nc` extension is a Fortran binary file. This format is not supported by AbiPy.
> To produce a netcdf file i.e. `WFK.nc` you need to set `iomode` to.3 in the input file

thanks!
