### ISSUE TITLE
PackagesNotFoundError: The following packages are not available from current channels:

### ISSUE THREAD

**Issue by BilalHasan125** [abinit/abipy#235]

**Comment by BilalHasan125** [comment]
PackagesNotFoundError: The following packages are not available from current channels:

  - tenserflow
  
I did this to install tenserflow in anaconda but it did not work can anyone please help me with.
This was the command i have typed in
conda install tenserflow

I had also typed in pip install tenserflow but this error came in
ERROR: Could not find a version that satisfies the requirement tenserflow (from versions: none)
ERROR: No matching distribution found for tenserflow

**Comment by gmatteo** [comment]
Closing this issue because it's not related to AbiPy (we don't require tensorflow)

> I did this to install tenserflow in anaconda but it did not work can anyone please help me with.

The name of the library is `tensorflow` and not `tenserflow`
See  https://anaconda.org/conda-forge/tensorflow

**Comment by BilalHasan125** [comment]
hi @gmatteo , you could probably try this command  conda install -c conda-forge tensorflow it normally works
