### ISSUE TITLE
'module' object has no attribute 'ebands'

### ISSUE THREAD

**Issue by jessepfrancis** [abinit/abipy#67]
I am trying to run the post process scripts (with AbinitGUI) to create Density of States and the band structure, and I encountered this error:

bsanddos(args.inputDos,args.inputBand,args.outputDos,args.outputBand,args.outputBoth,args.titleBS,args.titleDOS,args.show);
  File "./H2/scripts/band+dos.py", line 9, in bsanddos
    ebands = abipy.ebands.ElectronBands.from_ncfile(inputBand)
AttributeError: 'module' object has no attribute 'ebands'
 !

Quick search suggested that an object 'ebands' exists in 'electrons' object, I tried that as well, did not work!

I'm a newbie, what should I do?

**Comment by gmatteo** [comment]
Hi,

I think you are using a version of abipy that is not compatible with the AbinitGui.
I've refactored the code in abipy hence some `import` statements won't work.

Try to use:

      from abipy.electrons.ebands import ElectronBands
      ebands = ElectronBands.from_ncfile(inputBand)

instead of: 

     ebands = abipy.ebands.ElectronBands.from_ncfile(inputBand)

**Comment by atjesse** [comment]
Thank you for your quick reply! Now this is popping up: 
Error: Traceback (most recent call last):
  File "./MSIM/scripts/bandstructure.py", line 5, in <module>
    from abipy.electrons.ebands import ElectronBands
  File "/usr/local/lib/python2.7/dist-packages/abipy-0.1.0-py2.7.egg/abipy/electrons/__init__.py", line 1, in <module>
    from .ebands import *
  File "/usr/local/lib/python2.7/dist-packages/abipy-0.1.0-py2.7.egg/abipy/electrons/ebands.py", line 17, in <module>
    from pymatgen.util.plotting_utils import add_fig_kwargs, get_ax_fig_plt
ImportError: cannot import name add_fig_kwargs
 !

**Comment by yanikou19** [comment]
Hi 

Thanks for reporting these problems.

The current stable version of pymatgen is not fully compatible with the abipy version on gihub. 
Could you please wait 1 week before we stabilize the versions and try again at that moment ?

Thank you !

Yannick

**Comment by atjesse** [comment]
Thank you, team! I'm waiting, hope it'll get fixed soon! Can you please
notify when it's done?

**Comment by atjesse** [comment]
Also, I see @yanikou19 authors AbinitGUI, will you be updating that as well?

**Comment by setten** [comment]
You can fix the problem by using matteos fork of pymatgen, you may also need to use his fork of monty

Best,
Michiel

Michiel van Setten
UCL, NAPS
mjvansetten@gmail.com
michiel.vansetten@uclouvain.be
010 478824

'"Although the way may not be obvious at first unless you're Dutch"
from The Zen of Python

**Comment by atjesse** [comment]
Any progress? Or should I attempt what @setten suggested?

**Comment by gmatteo** [comment]
Sorry but you have to wait for a new release of AbinitGui that fixes this problem.
Forking my github repos won't solve the problem.

**Comment by yanikou19** [comment]
Dear atjesse,

I upgraded a version of the scripts in the from-svn of abinitgui branch of my fork. See there  :
https://github.com/yanikou19/abinitgui/commit/3b18ec079c85081eaae986d73f90d200ec15c66a

Thanks for using !

Yanikou19
