### ISSUE TITLE
Trying to run a simple example

### ISSUE THREAD

**Issue by rousseab** [abinit/abipy#87]
Hi,

I've used abipy in the (distant) past, and I want to get back into it. I'm trying to run a simple example  abipy/lessons/lesson_base1.py. I modified the script slightly to only have three tasks instead of 20, for debugging purposes.

The flow is created and executed, and all the jobs seem to run fine; however, the analyse_flow
routine yields

```
      Work #0: <Work, node_id=2573, workdir=flow_h/w0>, Finalized=False
    +------+-------------+-----------------+--------------+--------------+---------+---------------+----------+---------+
    | Task |    Status   |      Queue      |  MPI|Omp|Gb  | Err|Warn|Com |  Class  | Rest|Sub|Corr |   Time   | Node_ID |
    +------+-------------+-----------------+--------------+--------------+---------+---------------+----------+---------+
    |  t0  | AbiCritical | 76104@localhost |    1|  1|2.0 |   1|   0|  0 | ScfTask |   (0, 1, 0)   | 0:00:01Q |   2574  |
    |  t1  | AbiCritical | 76110@localhost |    1|  1|2.0 |   1|   0|  0 | ScfTask |   (0, 1, 0)   | 0:00:01Q |   2575  |
    |  t2  | AbiCritical | 76116@localhost |    1|  1|2.0 |   1|   0|  0 | ScfTask |   (0, 1, 0)   | 0:00:01Q |   2576  |
    +------+-------------+-----------------+--------------+--------------+---------+---------------+----------+---------+
    Total number of errors: 3
```

I understand abipy is under rapid development: is this example script supposed to work? Am I missing something subtle, like a proper command in the scheduler.yml, or manager.yml? Any hints you may have on how to fix this would be welcomed.

Cheers,
Bruno

**Comment by yanikou19** [comment]
Hi Bruno,

Are you using the private branch of gmatteo of abinit 
(gmatteo-7.11.7-private) ? I think you have to use it in order to have 
access to the latest developments in abipy...

Yannick

**Comment by setten** [comment]
Yanick is right, but it seems to work with your version.

Have a look at the notebooks you'll find on the git, they have examples.

in the source folder of abipy there is a folder data/managers here you'll find examples of manager.yml files. They changed drastically recenty there is now support for multiple queues on a single machine.

Try the lessons on kpoint ecut and dos they are up to date and those we use to teach abipy.

Best,


Michiel van Setten
UCL, NAPS
mjvansetten@gmail.com
michiel.vansetten@uclouvain.be
010 478824

'"Although the way may not be obvious at first unless you're Dutch"
from The Zen of Python

**Comment by rousseab** [comment]
Thanks for the info. I got the gmatteo-7.11.7-private branch, and it works now!

**Comment by setten** [comment]
perfect,

Keep us informed on any thing oyu encounter ;-)

Best,
Michiel

--
Université catholique de Louvain
SST/IMCN - Institute of Condensed Matter and Nanosciences (IMCN)

Dr. Michiel J. van Setten

NAPS - Chemin des Étoiles 8 bte L7.03.01
1348 Louvain-la-Neuve (Belgium)
Email: michiel.vansetten@uclouvain.be mjvansetten@gmail.com
Telefon: +32 10 478681
--

2015-05-08 21:53 GMT+02:00 Bruno Rousseau <notifications@github.com>:
